// 資材定義ファイル
// 資材を追加・編集する場合はこのファイルを変更してください

const MATERIALS = [
  {
    id: 'berabon',
    name: 'ベラボン',
    tooltip: 'ヤシ殻由来の軽い素材です。通気性が高く、根が伸びやすい環境を作ります。',
    shape: 'square',
    color: '#92400E',
    sizes: {
      S: { min: 5,  max: 8  }, // mm
      M: { min: 8,  max: 15 },
      L: { min: 15, max: 25 },
    },
    physics: {
      friction:    0.7,
      frictionAir: 0.08,
      density:     0.0008,
      restitution: 0,
    },
    params: {
      drainage:       70,
      waterRetention: 60,
      aeration:       80,
      organic:        true,
    },
    advanced: {
      porosity:        85, // 空隙率
      coarseRatio:     55, // 粗粒比率（細粒 = 100 - coarseRatio）
      compressibility: 40, // 圧縮率
      infiltration:    70, // 浸透速度
    },
  },
  {
    id: 'hyuga',
    name: '日向土',
    tooltip: '硬くて崩れにくい石です。排水性が高く、用土の骨格を保ちます。',
    shape: 'circle',
    color: '#A8A29E',
    sizes: {
      S: { min: 2,  max: 5  }, // mm
      M: { min: 5,  max: 10 },
      L: { min: 10, max: 18 },
    },
    physics: {
      friction:    0.5,
      frictionAir: 0.05,
      density:     0.002,
      restitution: 0,
    },
    params: {
      drainage:       85,
      waterRetention: 30,
      aeration:       85,
      organic:        false,
    },
    advanced: {
      porosity:        55,
      coarseRatio:     75,
      compressibility: 15,
      infiltration:    85,
    },
  },
  {
    id: 'akadama',
    name: '赤玉土',
    tooltip: '関東ローム層由来の粒状土です。保水性と排水性のバランスが良く、多くの植物に使われます。',
    shape: 'circle',
    color: '#C2410C',
    sizes: {
      S: { min: 2,  max: 5  },
      M: { min: 5,  max: 10 },
      L: { min: 10, max: 15 },
    },
    physics: {
      friction:    0.6,
      frictionAir: 0.06,
      density:     0.0018,
      restitution: 0,
    },
    params: {
      drainage:       65,
      waterRetention: 60,
      aeration:       60,
      organic:        false,
    },
    advanced: {
      porosity:        55,
      coarseRatio:     60,
      compressibility: 60,
      infiltration:    65,
    },
  },
  {
    id: 'pumice',
    name: '軽石',
    tooltip: '火山由来の多孔質な石です。非常に軽く、通気性・排水性が抜群です。',
    shape: 'circle',
    color: '#E5E5E5',
    sizes: {
      S: { min: 2,  max: 5  },
      M: { min: 5,  max: 10 },
      L: { min: 10, max: 18 },
    },
    physics: {
      friction:    0.55,
      frictionAir: 0.04,
      density:     0.0008,
      restitution: 0,
    },
    params: {
      drainage:       90,
      waterRetention: 20,
      aeration:       90,
      organic:        false,
    },
    advanced: {
      porosity:        80,
      coarseRatio:     80,
      compressibility: 10,
      infiltration:    90,
    },
  },
  {
    id: 'zeolite',
    name: 'ゼオライト',
    tooltip: 'ミネラルを多く含む多孔質な鉱物です。根腐れ防止や保水調整に使われます。',
    shape: 'square',
    color: '#FDE68A',
    sizes: {
      S: { min: 1,  max: 3  },
      M: { min: 3,  max: 6  },
      L: { min: 6,  max: 10 },
    },
    physics: {
      friction:    0.65,
      frictionAir: 0.07,
      density:     0.002,
      restitution: 0,
    },
    params: {
      drainage:       40,
      waterRetention: 80,
      aeration:       50,
      organic:        false,
    },
    advanced: {
      porosity:        70,
      coarseRatio:     30,
      compressibility: 20,
      infiltration:    45,
    },
  },
  {
    id: 'perlite',
    name: 'パーライト',
    tooltip: '膨張させた火山ガラスの粒です。非常に軽く、通気性の向上に役立ちます。',
    shape: 'circle',
    color: '#F8FAFC',
    sizes: {
      S: { min: 1,  max: 3  },
      M: { min: 3,  max: 6  },
      L: { min: 6,  max: 10 },
    },
    physics: {
      friction:    0.4,
      frictionAir: 0.05,
      density:     0.0005,
      restitution: 0,
    },
    params: {
      drainage:       85,
      waterRetention: 25,
      aeration:       90,
      organic:        false,
    },
    advanced: {
      porosity:        85,
      coarseRatio:     70,
      compressibility: 15,
      infiltration:    85,
    },
  },
  {
    id: 'vermiculite',
    name: 'バーミキュライト',
    tooltip: '加熱膨張させた鉱物です。保水性と保肥性が高く、種まきや育苗によく使われます。',
    shape: 'square',
    color: '#CA8A04',
    sizes: {
      S: { min: 1,  max: 3  },
      M: { min: 3,  max: 6  },
      L: { min: 6,  max: 12 },
    },
    physics: {
      friction:    0.55,
      frictionAir: 0.07,
      density:     0.0006,
      restitution: 0,
    },
    params: {
      drainage:       50,
      waterRetention: 75,
      aeration:       70,
      organic:        false,
    },
    advanced: {
      porosity:        75,
      coarseRatio:     40,
      compressibility: 50,
      infiltration:    55,
    },
  },
  {
    id: 'bark',
    name: '発酵バーク',
    tooltip: '樹皮を発酵・堆肥化した有機素材です。通気性と保水性を兼ね備え、土をふかふかにします。',
    shape: 'square',
    color: '#78350F',
    sizes: {
      S: { min: 5,  max: 10 },
      M: { min: 10, max: 20 },
      L: { min: 20, max: 35 },
    },
    physics: {
      friction:    0.75,
      frictionAir: 0.09,
      density:     0.0007,
      restitution: 0,
    },
    params: {
      drainage:       65,
      waterRetention: 65,
      aeration:       70,
      organic:        true,
    },
    advanced: {
      porosity:        70,
      coarseRatio:     65,
      compressibility: 45,
      infiltration:    65,
    },
  },
  {
    id: 'charcoal',
    name: '炭',
    tooltip: '木炭や竹炭を砕いたものです。通気性を高め、雑菌の抑制にも効果があります。',
    shape: 'square',
    color: '#292524',
    sizes: {
      S: { min: 3,  max: 6  },
      M: { min: 6,  max: 12 },
      L: { min: 12, max: 20 },
    },
    physics: {
      friction:    0.6,
      frictionAir: 0.05,
      density:     0.001,
      restitution: 0,
    },
    params: {
      drainage:       75,
      waterRetention: 35,
      aeration:       80,
      organic:        true,
    },
    advanced: {
      porosity:        80,
      coarseRatio:     75,
      compressibility: 20,
      infiltration:    75,
    },
  },
  {
    id: 'kanuma',
    name: '鹿沼土',
    tooltip: '栃木県鹿沼産の酸性火山土です。通気性と適度な保水性を持ち、ツツジや山野草に多く使われます。',
    shape: 'circle',
    color: '#D4A040',
    sizes: {
      S: { min: 2,  max: 5  },
      M: { min: 5,  max: 10 },
      L: { min: 10, max: 15 },
    },
    physics: {
      friction:    0.6,
      frictionAir: 0.06,
      density:     0.0017,
      restitution: 0,
    },
    params: {
      drainage:       70,
      waterRetention: 55,
      aeration:       65,
      organic:        false,
    },
    advanced: {
      porosity:        60,
      coarseRatio:     65,
      compressibility: 55,
      infiltration:    70,
    },
  },
  {
    id: 'peatmoss',
    name: 'ピートモス',
    tooltip: '湿地の植物が堆積した有機素材です。酸性で保水性が非常に高く、ブルーベリーや挿し木の土台に使われます。',
    shape: 'square',
    color: '#292524',
    sizes: {
      S: { min: 1,  max: 3  },
      M: { min: 3,  max: 8  },
      L: { min: 8,  max: 15 },
    },
    physics: {
      friction:    0.8,
      frictionAir: 0.10,
      density:     0.0005,
      restitution: 0,
    },
    params: {
      drainage:       35,
      waterRetention: 85,
      aeration:       55,
      organic:        true,
    },
    advanced: {
      porosity:        75,
      coarseRatio:     20,
      compressibility: 70,
      infiltration:    35,
    },
  },
  {
    id: 'humus',
    name: '腐葉土',
    tooltip: '落ち葉が分解した有機素材です。土をふかふかにして保水性と通気性を高める、培養土の基本素材です。',
    shape: 'square',
    color: '#3B2F1E',
    sizes: {
      S: { min: 3,  max: 8  },
      M: { min: 8,  max: 15 },
      L: { min: 15, max: 25 },
    },
    physics: {
      friction:    0.75,
      frictionAir: 0.09,
      density:     0.0007,
      restitution: 0,
    },
    params: {
      drainage:       55,
      waterRetention: 70,
      aeration:       65,
      organic:        true,
    },
    advanced: {
      porosity:        65,
      coarseRatio:     45,
      compressibility: 60,
      infiltration:    55,
    },
  },
  {
    id: 'sphagnum',
    name: '水苔',
    tooltip: '湿地に生育するコケを乾燥させたものです。保水力が非常に高く、洋ランや着生植物によく使われます。',
    shape: 'square',
    color: '#C7B99A',
    sizes: {
      S: { min: 5,  max: 10 },
      M: { min: 10, max: 20 },
      L: { min: 20, max: 40 },
    },
    physics: {
      friction:    0.85,
      frictionAir: 0.12,
      density:     0.0004,
      restitution: 0,
    },
    params: {
      drainage:       60,
      waterRetention: 90,
      aeration:       70,
      organic:        true,
    },
    advanced: {
      porosity:        85,
      coarseRatio:     50,
      compressibility: 65,
      infiltration:    60,
    },
  },
];
